[project]
name = "fooling-xai"
version = "0.1.0"
description = "Who cares"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "ipython>=9.7.0",
    "jupyterlab>=4.4.10",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
